### ISSUE TITLE
Response doesn't send

### ISSUE THREAD

**Issue by CDWizard** [NayanUnni95/TelegramBot#3]
# Bug Report:
The system's current song request handling mechanism is not thread-safe. When multiple requests are received concurrently, a race condition occurs, causing the initial request to be lost.

When multiple users simultaneously request a song, only the latest request is processed. This prevents the initial requester from receiving a response.

**Comment by NayanUnni95** [comment]
This issue will be fixed soon

**Comment by NayanUnni95** [comment]
Thank U I appreciate your prompt and valuable response.
